# Generated by Django 3.1.3 on 2021-10-26 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='account_number',
            field=models.IntegerField(unique=True),
        ),
    ]
