# Generated by Django 3.1.3 on 2021-10-26 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='data',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='otp',
            field=models.IntegerField(unique=True),
        ),
    ]
